pipeline:
  build:
    image: golang:1.7
    environment:
      - GOPATH=/drone
    commands:
      - go get github.com/kardianos/govendor
      - go get github.com/GeertJohan/go.rice
      - go get github.com/GeertJohan/go.rice/rice
      - "$GOPATH/bin/govendor sync -v"
      - "$GOPATH/bin/govendor test -cover -v +local"
      - "cd cmd/catgi && rice embed-go && go build; cd ../.."
      - "cd cmd/makepass && rice embed-go && go build; cd ../.."