pipeline:
  clone:
    image: plugins/git
    skip_verify: true
  build:
    image: golang:1.7
    environment:
      - GOPATH=/drone
    commands:
      - go get github.com/kardianos/govendor
      - "$GOPATH/bin/govendor sync -v"
      - "$GOPATH/bin/govendor test -cover -v +local"
      - "cd cmd/catgi && go build; cd ../.."
      - "cd cmd/makepass && go build; cd ../.."