language: go
go:
- 1.7.x
go_import_path: git.timschuster.info/rls.moe/catgi
install:
- go get github.com/kardianos/govendor
- "$GOPATH/bin/govendor fetch -v +all"
script:
- go test -v ./...
- cd cmd/catgi && go build; cd ../..
- cd cmd/makepass && go build; cd ../..
deploy:
  provider: releases
  api_key:
    secure: s6jxrhSdP+NkYVGmnZAm4RfEI5KP5cCuz7GKTSZrhSjuKASpAYIMebY4wf4EdaSdXWpsoXIcgfT+gk96ei4EQ88mbrfdBYy6RqFrwfJO+w14BvNcSR5jQprP4ILYAar4TZwOl60KPtu/6eLv/foKFGw593ZJdMLZi4F5C5rBEMv7PgagmuBbFY46k53wGk5dDL+y9+5lDjdwK2gFUNlbZmFOurv4Eyh5fzRAMB4+xzhAQQ21yfQqk2KFeOKy+B4xDG0HIEhX1e+mRvQkY4+ZmiHk/GPtZ4h9EzcYFPJAP9C+q2xd9kfsDm8q8j5sNO/Zp/D7uHj/avgT8RjFG7HKj+OpM0zwxJOYgatdjxnQ2oOegg0UugK2dZUE/1QQDgk35NspiOqPPBnXF0E8btUFGFd/NHTbfErgzp6RRVCswwd9+D4VfGEQcBEnt/A46psBG2frq4EiUwAn6e1tsoO+KxpCgxmULqCaoVFbtI/Nl6w1974xIS0vjMgV7FysWWm4cAkJJNs5fhv//AhWt3aRJ3mS7SzFgt6eft04DC0Wmp76XqN/140VnDeRAymWJwtLJJzBjdiP2x7cFPjFbdUeo6Ilsj0HN3BCiTPlt/62Z4N+J6oXWuo/BhjPXdhWUT2mWrtP4I3cm0dvTOueHuriI/7IxkVyL4gAoyMdoYnexxA=
  file: cmd/catgi/catgi
  on:
	tags: true